#!/usr/bin/env node
"use strict";

// context-index.js — keep AGENTS.md small while indexing CONTEXT.md.
// Usage:
//   node scripts/context-index.js update
//   node scripts/context-index.js list
//   node scripts/context-index.js query "term"
//   node scripts/context-index.js section "Rules"

import fs from "fs";
import path from "path";

const START = "<!-- context-harness:index:start -->";
const END = "<!-- context-harness:index:end -->";

const PURPOSES = {
  Project: "identity and purpose",
  Structure: "repo map",
  Rules: "constraints, habits, objectives",
  Workflow: "setup, run, test, lint, deploy",
  Language: "canonical terms",
  Relationships: "durable invariants",
  "Flagged Ambiguities": "resolved meaning conflicts",
  "Learned Patterns": "durable lessons",
};

const command = process.argv[2] || "update";
const arg = process.argv[3] || "";
const root = findProjectRoot(process.cwd());
const contextFile = path.join(root, "CONTEXT.md");
const agentsFile = path.join(root, "AGENTS.md");

main();

function main() {
  const context = readTextSafe(contextFile);
  if (!context) {
    console.error("CONTEXT.md not found.");
    process.exit(1);
  }

  if (command === "update") {
    updateAgents(context);
    return;
  }

  if (command === "list") {
    process.stdout.write(renderIndex(context));
    return;
  }

  if (command === "section") {
    printSection(context, arg);
    return;
  }

  if (command === "query") {
    queryIndex(context, arg);
    return;
  }

  console.error("Usage: node scripts/context-index.js [update|list|query|section] [text]");
  process.exit(1);
}

function updateAgents(context) {
  const current = readTextSafe(agentsFile) || defaultAgents();
  const block = renderIndex(context).trimEnd();
  const next = replaceManagedBlock(current, block);
  fs.writeFileSync(agentsFile, `${next.trimEnd()}\n`);
  console.log(`Updated ${path.relative(root, agentsFile)} from CONTEXT.md.`);
}

function renderIndex(context) {
  const sections = parseSections(context).filter((section) => section.level === 2);
  const lines = [
    "## Context Index",
    START,
    "Generated by `node scripts/context-index.js update`; open only relevant sections.",
    "",
    "- `NOW.md` - read first on start/resume.",
  ];

  for (const section of sections) {
    const childText = section.children.length
      ? ` Sub: ${section.children.map((child) => child.title).join(", ")}.`
      : "";
    lines.push(`- \`CONTEXT.md#${section.anchor}\` - ${describeSection(context, section)}.${childText}`);
  }

  lines.push(END);
  return `${lines.join("\n")}\n`;
}

function replaceManagedBlock(text, block) {
  const start = text.indexOf(START);
  const end = text.indexOf(END);
  if (start !== -1 && end !== -1 && end > start) {
    const prefix = text.slice(0, start);
    const headingMatch = prefix.match(/(?:^|\n)(?:## Context Index\s*\n\s*)+$/u);
    const replaceStart = headingMatch
      ? prefix.length - headingMatch[0].length + (headingMatch[0].startsWith("\n") ? 1 : 0)
      : start;
    const before = text.slice(0, replaceStart).replace(/[ \t]*$/u, "");
    const after = text.slice(end + END.length).replace(/^\s*/u, "\n");
    return `${before}${block}${after}`;
  }
  return `${text.trimEnd()}\n\n${block}`;
}

function defaultAgents() {
  return `# Agent Instructions
<!-- context-harness:schema v2 -->

## Context Contract
- At session start/resume, read \`NOW.md\` first, then use the Context Index below to choose relevant \`CONTEXT.md\` sections.
- Before planning or editing, respect \`CONTEXT.md\` \`## Rules\`.
- If the user teaches a durable term, invariant, workflow, constraint, or
  correction, update \`CONTEXT.md\` before it scrolls away.
- Route task-local findings and decisions to \`PLAN.md\`; durable lessons to
  \`CONTEXT.md\`.
- After updating \`CONTEXT.md\`, run \`node scripts/context-index.js update\`.
- Before ending, update \`NOW.md\` with current focus, blockers, next step, and
  touched files.
`;
}

function parseSections(context) {
  const sections = [];
  let currentH2 = null;
  for (const line of context.split("\n")) {
    const match = line.match(/^(##|###)\s+(.+?)\s*$/u);
    if (!match) continue;
    const section = {
      level: match[1].length,
      title: match[2].replace(/`/g, ""),
      anchor: anchorFor(match[2]),
      children: [],
    };
    if (section.level === 2) {
      sections.push(section);
      currentH2 = section;
    } else if (section.level === 3 && currentH2) {
      currentH2.children.push(section);
      sections.push(section);
    }
  }
  return sections;
}

function describeSection(context, section) {
  if (PURPOSES[section.title]) return PURPOSES[section.title];
  const body = readSection(context, section.title);
  const first = body
    .split("\n")
    .map((line) => line.trim())
    .find((line) => line && !line.startsWith("<!--") && !line.startsWith("```"));
  return first ? truncate(cleanMarkdown(first), 90) : "context section";
}

function printSection(context, heading) {
  if (!heading) {
    console.error("Provide a section heading.");
    process.exit(1);
  }
  const body = readSection(context, heading);
  if (!body.trim()) {
    console.error(`Section not found: ${heading}`);
    process.exit(1);
  }
  process.stdout.write(`## ${heading}\n${body.trimEnd()}\n`);
}

function queryIndex(context, query) {
  const terms = query
    .toLowerCase()
    .split(/\s+/u)
    .map((term) => term.trim())
    .filter(Boolean);
  if (!terms.length) {
    console.error("Provide a query term.");
    process.exit(1);
  }

  const matches = parseSections(context)
    .filter((section) => section.level === 2)
    .map((section) => {
      const body = readSection(context, section.title);
      const haystack = `${section.title}\n${body}`.toLowerCase();
      return { section, body, hit: terms.every((term) => haystack.includes(term)) };
    })
    .filter((entry) => entry.hit);

  if (!matches.length) {
    console.log("No matching CONTEXT.md sections.");
    return;
  }

  for (const { section, body } of matches) {
    console.log(`- CONTEXT.md#${section.anchor} (${section.title})`);
    const snippet = body
      .split("\n")
      .map((line) => cleanMarkdown(line.trim()))
      .find((line) => line && terms.some((term) => line.toLowerCase().includes(term)));
    if (snippet) console.log(`  ${truncate(snippet, 120)}`);
  }
}

function anchorFor(title) {
  return title
    .toLowerCase()
    .replace(/`/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

function cleanMarkdown(line) {
  return line
    .replace(/^[-*]\s+/u, "")
    .replace(/^\d+\.\s+/u, "")
    .replace(/[`*_]/g, "")
    .trim();
}

function truncate(text, max) {
  if (text.length <= max) return text;
  return `${text.slice(0, max - 3).trimEnd()}...`;
}

function readTextSafe(file) {
  try {
    return fs.readFileSync(file, "utf8");
  } catch {
    return "";
  }
}

function findProjectRoot(startDir) {
  const markers = [
    "package.json",
    "pyproject.toml",
    "Cargo.toml",
    "go.mod",
    "Gemfile",
    ".git",
  ];
  let current = path.resolve(startDir);
  while (current !== path.dirname(current)) {
    if (markers.some((marker) => fs.existsSync(path.join(current, marker)))) return current;
    current = path.dirname(current);
  }
  return startDir;
}

function readSection(markdown, heading) {
  const escaped = heading.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  const headingRe = new RegExp(`^(#{1,6})\\s+${escaped}\\s*$`);
  const lines = markdown.split("\n");
  const out = [];
  let currentDepth = 0;
  let inSection = false;
  for (const line of lines) {
    const match = line.match(headingRe);
    if (match && !inSection) {
      inSection = true;
      currentDepth = match[1].length;
      continue;
    }
    if (inSection) {
      const boundary = line.match(/^(#{1,6})\s+/);
      if (boundary && boundary[1].length <= currentDepth) break;
      out.push(line);
    }
  }
  return out.join("\n");
}
